name: Build

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install musl-tools
      run: sudo apt install -y musl-tools

    - name: Compile
      run: |
        make workflow

    - name: Make release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "runprocs"

